name: Setup Environment File

on:
  push:
    branches:
      - main

jobs:
  setup-env:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create .env File
        run: echo "GIPHY_API_KEY=${{ secrets.GOOGLE_GEMINI_API_KEY }}" > .env

      - name: Display .env File
        run: cat .env
